# Generated by Django 2.0.6 on 2018-06-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='gravatar_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='hireable',
            field=models.CharField(max_length=256),
        ),
    ]
